# Generated by Django 3.0.3 on 2020-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_f',
        ),
    ]
