# Generated by Django 3.0.3 on 2020-02-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20200213_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'emails'},
        ),
    ]
